// Generated by gencpp from file odometer_mecanum/robot_speed.msg
// DO NOT EDIT!


#ifndef ODOMETER_MECANUM_MESSAGE_ROBOT_SPEED_H
#define ODOMETER_MECANUM_MESSAGE_ROBOT_SPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace odometer_mecanum
{
template <class ContainerAllocator>
struct robot_speed_
{
  typedef robot_speed_<ContainerAllocator> Type;

  robot_speed_()
    : vx(0.0)
    , vy(0.0)
    , w(0.0)  {
    }
  robot_speed_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , vy(0.0)
    , w(0.0)  {
    }



   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;

   typedef double _w_type;
  _w_type w;




  typedef boost::shared_ptr< ::odometer_mecanum::robot_speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::odometer_mecanum::robot_speed_<ContainerAllocator> const> ConstPtr;

}; // struct robot_speed_

typedef ::odometer_mecanum::robot_speed_<std::allocator<void> > robot_speed;

typedef boost::shared_ptr< ::odometer_mecanum::robot_speed > robot_speedPtr;
typedef boost::shared_ptr< ::odometer_mecanum::robot_speed const> robot_speedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::odometer_mecanum::robot_speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::odometer_mecanum::robot_speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace odometer_mecanum

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'odometer_mecanum': ['/home/home/csc_home_prj/src/odometer_mecanum/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::odometer_mecanum::robot_speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::odometer_mecanum::robot_speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odometer_mecanum::robot_speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odometer_mecanum::robot_speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odometer_mecanum::robot_speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odometer_mecanum::robot_speed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::odometer_mecanum::robot_speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "461e74593b26c77a7c97f00fe82c6d79";
  }

  static const char* value(const ::odometer_mecanum::robot_speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x461e74593b26c77aULL;
  static const uint64_t static_value2 = 0x7c97f00fe82c6d79ULL;
};

template<class ContainerAllocator>
struct DataType< ::odometer_mecanum::robot_speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "odometer_mecanum/robot_speed";
  }

  static const char* value(const ::odometer_mecanum::robot_speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::odometer_mecanum::robot_speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 vx\n\
float64 vy\n\
float64 w\n\
";
  }

  static const char* value(const ::odometer_mecanum::robot_speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::odometer_mecanum::robot_speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct robot_speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::odometer_mecanum::robot_speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::odometer_mecanum::robot_speed_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ODOMETER_MECANUM_MESSAGE_ROBOT_SPEED_H
